baseURL: https://j-penny.com/
languageCode: en-gb
title: John Penny | Web Developer
theme: hugo-profile

Paginate: 3
# disqusShortname: #########
# googleAnalytics: #########

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "John Penny | Web Developer"
  description: Microsoft Certified Solutions Developer
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark/light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

    menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
      disableAchievements: true
  #     disableContact: true

  hero:
    enable: true
    intro: Hi, my name is
    title: John
    subtitle: I build distributed web applications
    content: I'm a Microsoft Certified Solutions Developer who chases the curve.
    image: /images/hero.svg
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jpenny1993
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jpenny93
        - icon: fab fa-twitter
          url: https://twitter.com/jpenny1993
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  about:
    enable: true
    title: "About Me"
    image: https://avatars.githubusercontent.com/u/10238181
    content: |
      I'm a passionate full stack .Net software developer with 7 years of industrial experience.
      My aim is to produce quality software, that is well documented, maintainable, and is horizontally scalable.

      I am proud to have contributed to production software used by UK police forces in North Yorkshire,
      Thames Valley, and Dubai.

      I have also collaborated on multiple integration systems for house
      builders and utility companies across the UK.

  skills:
    enable: true
    title: "Here are a few technologies I've been working with recently:"
    items:
      - "Bicep"
      - "Terraform"
      - "ASP.NET Core"
      - "ASP.NET MVC"
      - "T-SQL"
      - "Angular"
      - "Vue.js"
      - "Node"
      - "Unity3D"

  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Ligentia"
        companyUrl: "https://www.ligentia.com"
        date: "Jan 2022 - present"
        info:
          enable: true
          content: Ligentia is a global freight company that focuses on having a good work/life balance.
        content: |
          I'm a member of the technical debt team, my job is to redesign and build applications as microservices in Azure.

          I write automation scripts for both infrastructure and application deployment.
          I also spend a lot of time researching and documenting existing applications.

      - job: "Consultant Software Developer"
        company: "Audacia"
        companyUrl: "https://audacia.co.uk"
        date: "Oct 2016 - Dec 2021"
        # date: "Feb 2020 - Dec 2021"
        # - role: Senior Support Engineer
        #   companies:
        #   - Techbuyer:
        #     Functionality: Stock management
        #     Integrations: Scheduled FTP + SFTP uploads
        #     Technologies: ASP.Net Core, Angular
        #   - Gymfinity Kids:
        #     Functionality: Gym class management, bookings, purchases, discounts
        #     Integrations: Adyen
        #     Technologies: ASP.Net Core, Angular
        #   - Specialist Marine Consultants:
        #     Functionality: Windturbine maintenence planning, live ocean maps
        #     Technologies: ASP.Net Core, Angular
        #   - Story Homes:
        #     Functionality: House builders + sales
        #     Integrations: COINS, Salesforce
        #     Technologies: ASP.NET MVC, Vue.js
        #   - Bellway:
        #     Functionality: House builders
        #     Integrations: COINS
        #     Technologies: ASP.Net Core, Angular
        #   - 2M:
        #     Functionality: Chemical sales
        #     Technologies: ASP.Net Core
        #   - HSSMI & DETC:
        #     Functionality: House builders
        #     Technologies: ASP.Net Core, Angular
        #   - E-Car:
        #     Functionality: Car rental
        #     Technogies: ASP.NET MVC, Angular.js, cordova
        #   - Persimmon Homes:
        #     Functionality: Community enquiries portal
        #     Technologies: Umbraco
        #   - Innovative Trials:
        #     Technologies: ASP.Net Core, Angular
        # date: "Jan 2017 - Feb 2020"
        # - role: Lead Developer
        #   companies:
        #   - Aptus Utilities:
        #     Functionality: Asset Management, Tendering, Invoicing, Stock management
        #     Technologies:
        #     - ASP.Net MVC, Vue.js
        #     - ASP.Net Core API, Angular, Electron
        # date: "Oct 2016 - Jan 2017"
        # - role: Software Developer
        #   companies:
        #   - PPM Ltd:
        #     Functionality: Residential issue management
        #     Technologies: ASP.Net Web API, Xamarin Forms
        #   - Masta:
        #     Functionality: Appointment booking, Medical/vaccine treatments
        #     Technologies: ASP.Net Web MVC, Knockout.js
        #   - Story Homes:
        #     Functionality: House builder, Sales platform
        #     Technologies: ASP.Net Web MVC, Knockout.js
        #   - Huxloe:
        #     Functionality: Package delivery management
        #     Technologies: ASP.Net Web MVC, Knockout.js
        info:
          enable: true
          content: I changed roles 3 times during my employment in Audacia.
        content: |
          I was a Software Developer from Oct 2016 until Jan 2017.
          I worked for 4 companies developing ASP.NET MVC applications that ranged from residential issue management, medical treatments, building and selling houses, to delivering packages.

          I was a Lead Developer from Jan 2017 until Feb 2020.
          During this time I lead a team of developers to maintain and develop new features for an existing ASP.Net MVC website.
          We built an angular electron tablet app for accessing safety documents, and completing vehicle checklists.

          I was a Senior Devops & Production Support Engineer from Feb 2020 until Dec 2021.
          I taught a team of graduates how to supporting and develop new features for both new and legacy production systems.
          We had around 15 production systems with 4 hour SLA’s and 97% availability and uptime that covers over 1000 users per system.
          We covered a wide selection of technologies ranging from ASP.Net Web Forms, to ASP.Net Core.
          Nearing the end of my time at Audacia I made a major push to upgrade all systems from as low as Angular 2 and .Net Framework 4.5 to the lastest available platforms.

      - job: "Software Developer"
        company: "APD Communications"
        companyUrl: "http://web.archive.org/web/20161013235351/http://www.apdcomms.com/"
        date: "June 2015 - Oct 2016"
        featuredLink:
          enable: true
          name: "Video demonstration"
          url: "http://web.archive.org/web/20170112173606im_/http://www.apdcomms.com/videos/Artemis%20Demo1.mp4"
        content: |
          Most of my time has been spent developing AngularJS applications to improve the user's experience, such as; 
          - the dashboard & dashboard widgets
          - map client which displays a live view of vehicles 
          - and a graphical user interface for the SSRS reports server.

          I also wrote a loadtester for our gateway server. The gateway server was the endpoint service that all vehicles on the road would contact.
          Writing the loadtester was particularly challenging due to the fact that no legacy documentation existed for the gateway protocol, this meant that I had to reverse engineer the protocol from old Delphi code.
          My favourite sub-project was spending a day learning F# and suave.io. Then using that knowledge to write a new secure gateway server with a web management API.

          From May 2016 I became an Aspire team member. I developed an XMPP chat client to be shared between two products Cortex & Aspire. This will be so that dispatchers are able to contact call responders from inside our applications without having to use a third party.
          At the time there wasn't a library available that implemented the MUC feature, so I implemented this for the open source project before handing development back to the maintainer.

      - job: "Student Software Developer"
        company: "Seed Software"
        companyUrl: "http://web.archive.org/web/20140516190126/https://www.seedsoftware.co.uk/"
        date: "Sep 2014 - May 2015"
        info:
          enable: true
          content: Worked as a developer for the Alvis Register via Seed Software.
        featuredLink:
          enable: true
          name: "Customer website"
          url: "https://www.alvisregister.co.uk"
        content: |
          This was a part time position as part of the 08911 Commercial Development module at the University of Hull.
          Masters students were split into teams and given projects to manage and develop solutions to support real world customers.

          I was the Lead Developer for the **Alvis Register** project, our goal was to develop an application that could help identify and merge duplicate car records in their database, while also maintaining an existing website for the customer.
          We used agile development techniques such as SCRUM to help manage our project.

          My roles included:
          - leading customer meetings
          - building requirements
          - WPF application development
          - maintaining an ASP.Net MVC website

  education:
    enable: true
    # index: true
    items:
      - title: "Computer Science | MEng"
        school:
          name: "University of Hull"
          url: "https://www.hull.ac.uk"
        date: "Sept 2010 - June 2015"
        GPA: "80 out of 100"
        featuredLink:
          enable: true
          name: "Adafruit trinket goggles"
          url: "https://www.youtube.com/watch?v=MKQfDdQyHPc"
        content: |
          I graduated from the University of Hull with a 1st class degree.

          While at university I was very interested in electronics, during my free time I built and programmed a set of LED goggles for my mad scientise halloween costume.

      - title: "Secondary School"
        school:
          name: "St Bede's Catholic Grammar School, Bradford"
          url: "https://sbsj.co.uk"
        date: "Sept 2003 - July 2010"
        GPA: "BCC"
        content: |
          A2
            - Applied ICT
            - Geography
            - Mathematics

          AS
            - Physics

  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com

  projects:
    enable: true
    items:
      - title: RTSP Viewer
        content: Provides the ability to watch an RTP stream from my security camera without requiring VLC media player.
        image: https://github.com/jpenny1993/RtspViewer/raw/main/img/demo.png
        badges:
          - "C#"
          - "ffmpeg"
          - "Windows Forms"
          # - "UWP" TBA
        links:
          - icon: fab fa-github
            url: https://github.com/jpenny1993/RtspViewer

      - title: Gadgeteer Smart Sensor
        content: The beginnings of a smart home device, and an attempt to relive my university dissertation.
        image: https://github.com/jpenny1993/GT.NetworkCamera/raw/main/img/hardware.png
        badges:
          - "C#"
          - "Gadgeteer"
          - ".Net Micro Framework"
        links:
          - icon: fab fa-github
            url: https://github.com/jpenny1993/GT.NetworkCamera

      - title: Sharp.Xmpp
        content: I implemented multi-user chat rooms for a C# XMPP client.
        image: https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/XMPP_logo.svg/330px-XMPP_logo.svg.png
        featured:
          name: View project
          link: https://github.com/pgstath/Sharp.Xmpp
        badges:
          - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/jpenny1993/Sharp.Xmpp

  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: john@j-penny.com
    btnName: Contact me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/jpenny1993
      linkedin: https://www.linkedin.com/in/jpenny93
      twitter: https://twitter.com/jpenny1993